### ISSUE TITLE
Update / Generalise the Contributor T&Cs

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/the-developer-dao-foundation#4]
Love seeing the Contributor T&Cs go up @billyjitsu @TheWeb3Attorney ❤️ 

Can we update these to apply to all contributions on our GitHub rather than just this starter kit's work?

I noticed it is explicitly referencing the hackathons repo, and my understanding was we're moving the starter kits to their own [repo](https://github.com/Developer-DAO/web3-starter-kits), which is what got me thinking of this - a generalised one for all contributions (if possible) would mean we don't need to worry about these issues of things moving/being named something else

**Comment by billyjitsu** [comment]
This is a good idea, I will reach out!

**Comment by TheWeb3Attorney** [comment]
It has been updated on both Repos to D_D T&Cs.

**Comment by kempsterrrr** [comment]
My @TheWeb3Attorney is a legend amongst legend - tysm 🙏🏻
